# Generated by Django 4.2.7 on 2025-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_application_search_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_search',
            name='extra',
        ),
    ]
