# Generated by Django 4.2.7 on 2025-03-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_remove_application_search_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='days',
        ),
        migrations.RenameField(
            model_name='course_faculty',
            old_name='ssemester_id',
            new_name='semester_id',
        ),
    ]
